### PR TITLE
Explicitly disable audio for JSMPEG streams to remove spurious error message

### PR DESCRIPTION
**Pull request by dermotduffy**
* For #109

### CODE REVIEW

**Comment by Joeviocoe** [comment]
I could not find an answer when searching through old issues/PRs.

Is audio possible with the JSMPEG stream?

JSMPEG has lower lag than HA, but I do miss the ability to unmute and go fullscreen.

**Comment by dermotduffy** [comment]
I believe [JSMPEG](https://github.com/phoboslab/jsmpeg) as a technology does support audio, but (AFAIK) Frigate does not encode audio (and so the card cannot receive it).

**Comment by Joeviocoe** [comment]
I tried the WebRTC addons and integrations, several versions.  WebRTC doesn't support the audio.  For browsers that fallback to MSE, I get audio but it's has more lag and audio stutters trying to be real-time.

[native WebRTC](https://www.home-assistant.io/integrations/rtsp_to_webrtc/)
Seems a bit confusing.  Calling it native, but it requires an addon that runs a proxy server.

Also, if I set my live provider to "ha" in the frigate-hass-card, how do I tell if its viewing as HLS, LL-HLS, or WebRTC native?

My workaround right now:
My dashboard view (8 cameras, 8 cards), each card has two cameras (thank you for implementing multiple cameras per card).
The first camera in the card has a live view provider of JSMPEG, which is less than 1 second of delay.  
The other is HA which is delayed, but has audio.

This way, if I want audio, I can swipe to the other camera.  It would be nice to maybe feed audio from one provider into another provider's live feed.  Of course syncing would be needed.

Thanks.

**Comment by NickM-27** [comment]
I have tested with the webrtc card and it supported audio so may want to double check your setup on that.

To me native WebRTC makes sense, since it is the version of webbrtc that is "native" to HA.

**Comment by dermotduffy** [comment]
> Also, if I set my live provider to "ha" in the frigate-hass-card, how do I tell if its viewing as HLS, LL-HLS, or WebRTC native?

You cannot (easily).

> Seems a bit confusing. Calling it native, but it requires an addon that runs a proxy server.

[Might be a naming thing] No addon is required. Just an [integration](https://www.home-assistant.io/integrations/rtsp_to_webrtc/) that comes stock with Home Assistant and is maintained by Home Assistant (feels 'native' to me!).

**Comment by Joeviocoe** [comment]
The integration does not load without pointing it to a proxy server.
`The RTSPtoWebRTC integration requires a server to translate RTSP streams into WebRTC. Enter the URL to the RTSPtoWebRTC server.`

The webpage for the integration even says,
`The integration initiates a connection to a [RTSPtoWeb](https://github.com/deepch/RTSPtoWeb) or [RTSPtoWebRTC](https://github.com/deepch/RTSPtoWebRTC) proxy server that converts an RTSP stream to a WebRTC stream.`

I guess it's just semantics, but having to run a separate server (even if just a docker container addon) didn't seem "native" to me.
I've tried both addons.

Anyway, is it possible my cameras just don't support audio over WebRTC?  
Audio was not available for my Amcrest cams or my Hikvision doorbel cam.  But they do work with Frigate using the rtsp url.

It's very tough to troubleshoot when the card doesn't say what it's using.  I played around with the AlexxIT component for HA, using its custom:webrtc-camera card... and it too will work with WebRTC on some browsers, but no audio.  Some browsers would fallback to MSE and have audio though.
@NickM-27 with cards falling back and not necessarily using WebRTC, is it possible your audio feed was not using WebRTC?

**Comment by dermotduffy** [comment]
> The integration does not load without pointing it to a proxy server.

You're absolutely right, my apologies. The integration is built-in, but the proxy server / docker container is not [yet at least]

> It's very tough to troubleshoot when the card doesn't say what it's using. 

Certain not easy, but open your developer tools (F12) and use the element inspect to select the video player on the card:

* `frigate-card-ha-web-rtc-player`: WebRTC ("native")
* `frigate-card-ha-hls-player`: HLS or LL-HLS (not aware of a way to tell those apart)

**Comment by NickM-27** [comment]
Yeah same as @dermotduffy it confirms it is in webrtc mode and I also have amcrest camera, audio works fine

**Pull request merged**
